---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : hooligan
production_url : http://deadno.de

posts:
  permalink: /:categories/:title/
  summary_lines: 3
  latest: 5

pages:
  permalink: 'pretty'